const list360 = {
    totalPage: 44,
    content: [
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Giám đốc Thương mại",
          levelName: "E5",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "000059",
          staffName: "Nguyễn Xuân Tường",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "000059",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Giám đốc Điều hành",
          levelName: "E6",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "000163",
          staffName: "Nguyễn Minh Trí",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "000163",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Trưởng bộ phận Tiêu chuẩn Tài sản",
          levelName: "E2.1",
          unitName: "Corp",
          departmentName: "Khối Nhượng quyền",
          divisionName: "Phòng Thiết kế & Tiêu chuẩn",
          restaurantName: "Bộ phận Tiêu chuẩn Tài sản",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "011782",
          staffName: "Bùi Văn Hưng",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "011782",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Trưởng phòng Tiêu chuẩn Vận hành & Sản phẩm",
          levelName: "E3.1",
          unitName: "Corp",
          departmentName: "Khối Nhượng quyền",
          divisionName: "Phòng Tiêu chuẩn Vận hành & Sản phẩm",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "012422",
          staffName: "Phạm Thị Minh Huệ",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "012422",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Trưởng phòng Vận hành Tiêu chuẩn",
          levelName: "E3.1",
          unitName: "Corp",
          departmentName: "Khối Nhượng quyền",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0157039",
          staffName: "Hoàng Quốc Khánh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0157039",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Trưởng phòng Phát triển Kinh doanh",
          levelName: "E3.2",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0157042",
          staffName: "Trần Hoàng Trung",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0157042",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Giám đốc Điều hành",
          levelName: "E6",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0167912",
          staffName: "Hà Thúc Tú",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0167912",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Chuyên viên cao cấp Quản lý Dự án",
          levelName: "O3",
          unitName: "Corp",
          departmentName: "Khối Nhượng quyền",
          divisionName: "Phòng Thiết kế & Tiêu chuẩn",
          restaurantName: "Bộ phận Thiết kế & Xây dựng",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0169734",
          staffName: "Lê Phương Oanh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0169734",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Giám đốc Thương mại",
          levelName: "E4",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0172375",
          staffName: "Trần Việt Trung",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0172375",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
      {
        personEvaluated: {
          regionName: "Miền Bắc",
          positionName: "Giám đốc Kiểm toán Nội bộ",
          levelName: "E4",
          unitName: "Corp",
          departmentName: "Phòng Kiểm toán Nội bộ",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: null,
          staffID: "0177894",
          staffName: "Tăng Chí Minh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: null,
          email: null,
          surveyObject360: 0,
          superiorID: null,
        },
        assessor: {
          statusName: "Chưa khảo sát",
          regionName: "Miền Bắc",
          positionName: "Tổng giám đốc",
          levelName: "E7",
          unitName: "Corp",
          departmentName: "",
          divisionName: "",
          restaurantName: "",
          orderByRespondents: 0,
          staffKey: "0177894",
          staffID: "000058",
          staffName: "Đào Thế Vinh",
          regionID: null,
          unitID: null,
          departmentID: null,
          divisionID: null,
          restaurantID: null,
          positionID: null,
          levelID: null,
          phone: "0",
          email: "vinh.dao@ggg.com.vn",
          surveyObject360: 1,
          superiorID: null,
        },
      },
    ],
    page: 1,
    pageSize: 10,
};
  
export default list360;