const listMember = [
    {
      totalPage: 5,
      totalItem: 50,
      contents: [
        {
          orders: 1,
          staffID: "0000001",
          staffName: "Nguyễn Văn Tật",
          positionName: "RM",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nvt@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Đã khảo sát"
        },
        {
          orders: 2,
          staffID: "0000002",
          staffName: "Nguyễn Văn Đạt",
          positionName: "RM",
          levelName: "03",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nvd@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Chưa khảo sát"
        },
        {
          orders: 3,
          staffID: "0000003",
          staffName: "Nguyễn Căn Hạnh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nch@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Chưa khảo sát"
        },
        {
          orders: 4,
          staffID: "0000004",
          staffName: "Chu Hanh La",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "CHL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 5,
          staffID: "0000005",
          staffName: "Trần Công Danh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "TCD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 6,
          staffID: "0000006",
          staffName: "Trần Hữu Danh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "KD",
          phone: "0123456789",
          email: "THD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 7,
          staffID: "0000007",
          staffName: "Trần Danh Lam",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "KD",
          phone: "0123456789",
          email: "TDL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 8,
          staffID: "0000008",
          staffName: "Trần Hữu Lượng",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "QA",
          phone: "0123456789",
          email: "THL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 9,
          staffID: "0000009",
          staffName: "Chu Hữu Danh",
          positionName: "RM",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CHD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 10,
          staffID: "0000010",
          staffName: "Chu Nguyên Danh",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CND@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          orders: 11,
          staffID: "0000010",
          staffName: "Chu Nguyên Danh 2",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CND@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        }
      ]
    }
  ];

 export const listMember2 = [
        {
          id: 1,
          orders: 1,
          staffID: "0000001",
          staffName: "Nguyễn Văn Tật",
          positionName: "RM",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nvt@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Đã khảo sát"
        },
        {
          id: 2,
          orders: 2,
          staffID: "0000002",
          staffName: "Nguyễn Văn Đạt",
          positionName: "RM",
          levelName: "03",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nvd@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Chưa khảo sát"
        },
        {
          id: 3,
          orders: 3,
          staffID: "0000003",
          staffName: "Nguyễn Căn Hạnh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "nch@gmail.com",
          surveyObject360: "Cấp dưới",
          statusName: "Chưa khảo sát"
        },
        {
          id: 4,
          orders: 4,
          staffID: "0000004",
          staffName: "Chu Hanh La",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "CHL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 5,
          orders: 5,
          staffID: "0000005",
          staffName: "Trần Công Danh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "HR",
          phone: "0123456789",
          email: "TCD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 6,
          orders: 6,
          staffID: "0000006",
          staffName: "Trần Hữu Danh",
          positionName: "NV Phục Vụ",
          levelName: "02",
          unitName: "OPS",
          departmentName: "KD",
          phone: "0123456789",
          email: "THD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 7,
          orders: 7,
          staffID: "0000007",
          staffName: "Trần Danh Lam",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "KD",
          phone: "0123456789",
          email: "TDL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 8,
          orders: 8,
          staffID: "0000008",
          staffName: "Trần Hữu Lượng",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "QA",
          phone: "0123456789",
          email: "THL@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 9,
          orders: 9,
          staffID: "0000009",
          staffName: "Chu Hữu Danh",
          positionName: "RM",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CHD@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 10,
          orders: 10,
          staffID: "0000010",
          staffName: "Chu Nguyên Danh",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CND@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        },
        {
          id: 11,
          orders: 10,
          staffID: "0000010",
          staffName: "Chu Nguyên Danh",
          positionName: "Quản Lý",
          levelName: "02",
          unitName: "OPS",
          departmentName: "NS",
          phone: "0123456789",
          email: "CND@gmail.com",
          surveyObject360: "Cấp trên",
          statusName: ""
        }
  ];
export default listMember;